language: node_js
node_js:
  - "stable"

services:
  - postgresql

cache:
  directories:
    - "node_modules"

install:
  - yarn install

before_script:
  - psql -c 'create database propertytestdb;' -U postgres
  - yarn run test:db:migrate
script:
  - yarn run test
after_success:
  - yarn run coverage
  env:
  global:
    - CODECLIMATE_REPO_TOKEN=62ea5958c87f83dc6b0b28a34f0f9a0cb37a9580a51a0b1674727988089aee57