language: node_js
node_js:
  - "stable"

services:
  - postgresql

cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
  - psql -c 'create database propertytestdb;' -U postgres
  - npm run test:db:migrate
script:
  - npm run test
after_success:
  - npm run coverage
